services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\Oidc\:
    resource: '../Classes/*'

  Causal\Oidc\EventListener\FrontendLoginEventListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc'
        method: 'modifyLoginFormView'
        event: TYPO3\CMS\FrontendLogin\Event\ModifyLoginFormViewEvent

  Causal\Oidc\Service\OAuthService:
    public: true

  Causal\Oidc\Service\OpenIdConnectService:
    public: true

  Causal\Oidc\Factory\RequestFactory:
    public: true

  Causal\Oidc\Factory\GenericOAuthProviderFactory:
    public: true

  Causal\Oidc\EventListener\ProcessRequestTokenListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc-request-token'
        event: TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent

  Causal\Oidc\Frontend\FrontendSimulationV13:
    public: true

  Causal\Oidc\EventListener\GetAuthorizationUrlSetLanguageEventListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc-get-authorization-url-set-language'
        event: Causal\Oidc\Event\GetAuthorizationUrlEvent
